export const ui = {
  skipToContent: "मुख्य सामग्रीमा जानुहोस्",
  tagline: "पोखराबाट स्वतन्त्र समाचार",
  kicker: "समाचार · समुदाय · संस्कृति",
  navHome: "गृहपृष्ठ",
  navLatest: "ताजा समाचार",
  navSearch: "खोज्नुहोस्",
  navPrimary: "मुख्य नेभिगेसन",
  navMobile: "मोबाइल नेभिगेसन",
  navOpen: "नेभिगेसन मेनु खोल्नुहोस्",
  navClose: "नेभिगेसन मेनु बन्द गर्नुहोस्",
  navNavigate: "नेभिगेट गर्नुहोस्",
  navFooter: "फुटर नेभिगेसन",
  footerExplore: "अन्वेषण गर्नुहोस्",
  footerCopyright: "पोखराबाट स्वतन्त्र पत्रकारिता।",
  articleFeatured: "विशेष",
  articleAuthor: "लेखक",
  articlePublished: "प्रकाशित",
  articleUpdated: "अद्यावधिक",
  articleViews: "पटक हेरिएको",
  articleViewAll: "सबै हेर्नुहोस्",
  articleBreaking: "ताजा खबर",
  articleFocus: "विशेष फोकस",
  articleLatestUpdates: "पछिल्ला अपडेट",
  articleLatest: "ताजा समाचार",
  articleJustIn: "भर्खरै",
  articleMostRead: "धेरै पढिएका",
  articlePopular: "लोकप्रिय",
  articleTopStories: "प्रमुख समाचार",
  articleContinue: "पढिरहनुहोस्",
  articleContinueNav: "समाचार ब्राउज गर्नुहोस्",
  articleViewLatest: "ताजा समाचार हेर्नुहोस्",
  homeNewsroom: "समाचार कक्ष",
  homeEmptyTitle: "अहिलेसम्म कुनै समाचार प्रकाशित भएको छैन।",
  homeEmptyDescription:
    "प्रकाशित हुनेबित्तिकै पोखराबाटका ताजा समाचार यहाँ देखिनेछन्।",
  homeBannerTitle: "मुख्य समाचार",
  homeBannerLatest: "ताजा समाचार",
  searchLabel: "प्रकाशित समाचार खोज्नुहोस्",
  searchPlaceholder: "शीर्षक र सारांश खोज्नुहोस्",
  searchSubmit: "समाचार खोज्नुहोस्",
  paginationLabel: "समाचार पृष्ठक्रम",
  paginationPrevious: "अघिल्लो",
  paginationNext: "अर्को",
  pageNotFound: "पृष्ठ फेला परेन",
  pageUnavailable: "तपाईंले खोज्नुभएको पृष्ठ उपलब्ध छैन।",
  returnHome: "गृहपृष्ठमा फर्कनुहोस्",
} as const;

export function formatUiText(
  template: string,
  values: Record<string, string | number>,
) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    String(values[key] ?? ""),
  );
}
